package example;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SkillLevel implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String productCategory;
   private double amountLimit;
   private java.lang.String clerk;

   public SkillLevel()
   {
   }

   public java.lang.String getProductCategory()
   {
      return this.productCategory;
   }

   public void setProductCategory(java.lang.String productCategory)
   {
      this.productCategory = productCategory;
   }

   public double getAmountLimit()
   {
      return this.amountLimit;
   }

   public void setAmountLimit(double amountLimit)
   {
      this.amountLimit = amountLimit;
   }

   public java.lang.String getClerk()
   {
      return this.clerk;
   }

   public void setClerk(java.lang.String clerk)
   {
      this.clerk = clerk;
   }

   public SkillLevel(java.lang.String productCategory, double amountLimit,
         java.lang.String clerk)
   {
      this.productCategory = productCategory;
      this.amountLimit = amountLimit;
      this.clerk = clerk;
   }

}